// c:\Users\Admin\imoney-local\server_modules\gameData.js

export const INITIAL_BALANCE = 3000000;
export const BANK_START_RESERVE = 50000000;
export const LOAN_LIMIT_PERCENT = 0.80; // 80% dos bens
export const SELL_BANK_RATE = 0.5;
export const JAIL_BAIL = 50000;
export const ADMIN_PASSWORD = '@Matheus6584'; // Senha Mestra

export const TOURISM_IDS = ['av_beira_mar', 'av_niemeyer', 'jardim_botanico', 'marina_gloria', 'barra_tijuca', 'ponte_rio_niteroi'];

export const ITEM_NAMES = {
  'habeas_corpus': 'Habeas Corpus',
  'free_buy': 'Compra Livre',
  'steal_prop': 'Usucapião',
  'black_card': 'Cartão Black'
};

export const PROPERTIES_DB = [
  { id: 'av_beira_mar', name: 'Av. Beira Mar', group: 'light_green', price: 60000, rent: 2000, rent1: 10000, rent2: 30000, rent3: 90000, rent4: 160000, rentHotel: 250000, houseCost: 50000 },
  { id: 'av_niemeyer', name: 'Av. Niemeyer', group: 'light_green', price: 75000, rent: 4000, rent1: 20000, rent2: 60000, rent3: 180000, rent4: 320000, rentHotel: 450000, houseCost: 50000 },
  { id: 'jardim_botanico', name: 'Jardim Botânico', group: 'light_green', price: 100000, rent: 6000, rent1: 30000, rent2: 90000, rent3: 270000, rent4: 400000, rentHotel: 500000, houseCost: 50000 },
  { id: 'av_ipiranga', name: 'Av. Ipiranga', group: 'purple', price: 100000, rent: 8000, rent1: 40000, rent2: 100000, rent3: 300000, rent4: 450000, rentHotel: 600000, houseCost: 50000 },
  { id: 'av_sao_joao', name: 'Av. São João', group: 'purple', price: 120000, rent: 6000, rent1: 30000, rent2: 90000, rent3: 270000, rent4: 400000, rentHotel: 500000, houseCost: 50000 },
  { id: 'higienopolis', name: 'Higienópolis', group: 'pink', price: 400000, rent: 50000, rent1: 200000, rent2: 600000, rent3: 1400000, rent4: 1700000, rentHotel: 2000000, houseCost: 200000 },
  { id: 'jardins', name: 'Jardins', group: 'pink', price: 350000, rent: 35000, rent1: 175000, rent2: 500000, rent3: 1100000, rent4: 1300000, rentHotel: 1500000, houseCost: 200000 },
  { id: 'av_juscelino', name: 'Av. Juscelino K.', group: 'red', price: 240000, rent: 20000, rent1: 100000, rent2: 300000, rent3: 750000, rent4: 925000, rentHotel: 1100000, houseCost: 150000 },
  { id: 'av_ibirapuera', name: 'Av. Ibirapuera', group: 'red', price: 220000, rent: 18000, rent1: 90000, rent2: 250000, rent3: 700000, rent4: 875000, rentHotel: 1050000, houseCost: 150000 },
  { id: 'rua_oscar_freire', name: 'Rua Oscar Freire', group: 'red', price: 220000, rent: 18000, rent1: 90000, rent2: 250000, rent3: 700000, rent4: 875000, rentHotel: 1050000, houseCost: 150000 },
  { id: 'av_recife', name: 'Av. Recife', group: 'dark_green', price: 140000, rent: 10000, rent1: 50000, rent2: 150000, rent3: 450000, rent4: 625000, rentHotel: 750000, houseCost: 100000 },
  { id: 'ponte_guaiba', name: 'Ponte do Guaíba', group: 'dark_green', price: 140000, rent: 10000, rent1: 50000, rent2: 150000, rent3: 450000, rent4: 625000, rentHotel: 750000, houseCost: 100000 },
  { id: 'av_paulista', name: 'Av. Paulista', group: 'dark_green', price: 160000, rent: 12000, rent1: 60000, rent2: 180000, rent3: 500000, rent4: 700000, rentHotel: 900000, houseCost: 100000 },
  { id: 'viaduto_cha', name: 'Viaduto do Chá', group: 'dark_blue', price: 180000, rent: 14000, rent1: 70000, rent2: 200000, rent3: 550000, rent4: 750000, rentHotel: 950000, houseCost: 100000 },
  { id: 'rua_consolacao', name: 'Rua da Consolação', group: 'dark_blue', price: 180000, rent: 14000, rent1: 70000, rent2: 200000, rent3: 550000, rent4: 750000, rentHotel: 950000, houseCost: 100000 },
  { id: 'praca_se', name: 'Praça da Sé', group: 'dark_blue', price: 200000, rent: 16000, rent1: 80000, rent2: 220000, rent3: 600000, rent4: 800000, rentHotel: 1000000, houseCost: 100000 },
  { id: 'ponte_rio_niteroi', name: 'Ponte Rio-Niterói', group: 'yellow', price: 280000, rent: 26000, rent1: 130000, rent2: 360000, rent3: 850000, rent4: 1025000, rentHotel: 1200000, houseCost: 150000 },
  { id: 'marina_gloria', name: 'Marina da Glória', group: 'yellow', price: 260000, rent: 22000, rent1: 110000, rent2: 330000, rent3: 800000, rent4: 975000, rentHotel: 1150000, houseCost: 150000 },
  { id: 'barra_tijuca', name: 'Barra da Tijuca', group: 'yellow', price: 260000, rent: 22000, rent1: 110000, rent2: 330000, rent3: 800000, rent4: 975000, rentHotel: 1150000, houseCost: 150000 },
  { id: 'av_contorno', name: 'Av. do Contorno', group: 'orange', price: 300000, rent: 26000, rent1: 130000, rent2: 390000, rent3: 900000, rent4: 1100000, rentHotel: 1275000, houseCost: 200000 },
  { id: 'praca_castro_alves', name: 'Praça Castro Alves', group: 'orange', price: 300000, rent: 26000, rent1: 130000, rent2: 390000, rent3: 900000, rent4: 1100000, rentHotel: 1275000, houseCost: 200000 },
  { id: 'praca_tres_poderes', name: 'Praça dos Três Poderes', group: 'orange', price: 320000, rent: 28000, rent1: 150000, rent2: 450000, rent3: 1000000, rent4: 1200000, rentHotel: 1400000, houseCost: 200000 },
  { id: 'cia_mineracao', name: 'Cia de Mineração', group: 'company', price: 200000, multiplier: 50000, type: 'company', rent: 50000 },
  { id: 'cia_petrolifera', name: 'Cia Petrolífera', group: 'company', price: 200000, multiplier: 50000, type: 'company', rent: 50000 },
  { id: 'cia_agua', name: 'Cia Água e Saneam.', group: 'company', price: 200000, multiplier: 50000, type: 'company', rent: 50000 },
  { id: 'central_forca', name: 'Central Força e Luz', group: 'company', price: 200000, multiplier: 50000, type: 'company', rent: 50000 },
  { id: 'credito_carbono', name: 'Créditos de Carbono', group: 'special', price: 150000, multiplier: 40000, type: 'company', rent: 40000 },
  { id: 'ponto_com', name: 'Ponto.com', group: 'special', price: 150000, multiplier: 40000, type: 'company', rent: 40000 },
];

export const ALL_CARDS = [
  { type: 'item', title: 'Habeas Corpus', text: 'Seu advogado é muito bom. Guarde para sair da cadeia.', action: 'add_inventory', itemId: 'habeas_corpus' },
  { type: 'item', title: 'Compra Livre!', text: 'Uma oferta irrecusável. Compre qualquer imóvel ocupado.', action: 'add_inventory', itemId: 'free_buy' },
  { type: 'item', title: 'Usucapião', text: 'Tome posse de um imóvel de outro jogador de graça.', action: 'add_inventory', itemId: 'steal_prop' },
  { type: 'item', title: 'Cartão Black', text: 'Liquide sua dívida com o banco instantaneamente.', action: 'add_inventory', itemId: 'black_card' },
  { type: 'setback', title: 'Taxado na Shein', text: 'Suas "brusinhas" ficaram presas em Curitiba.', amount: 15000, action: 'pay_bank' },
  { type: 'setback', title: 'Curso de Day Trade', text: 'Comprou na alta, vendeu na baixa. Stonks reversos.', amount: 50000, action: 'pay_bank' },
  { type: 'setback', title: 'Harmonização Facial', text: 'Ficou parecendo o Lula Molusco Bonitão. Pague para consertar.', amount: 80000, action: 'pay_bank' },
  { type: 'setback', title: 'Terreno no Metaverso', text: 'Investiu milhões em pixels que não valem nada.', amount: 300000, action: 'pay_bank' },
  { type: 'setback', title: 'Urubu do Pix', text: 'Mandou 50k esperando voltar 500k. Não voltou.', amount: 50000, action: 'pay_bank' },
  { type: 'setback', title: 'Pensão Alimentícia', text: 'Atrasou de novo? O oficial de justiça te achou.', amount: 100000, action: 'pay_bank' },
  { type: 'setback', title: 'Batida de Carro', text: 'Bateu a Ferrari no poste tirando selfie.', amount: 200000, action: 'pay_bank' },
  { type: 'setback', title: 'CADEIA!', text: 'Lavagem de dinheiro descoberta. O xadrez te espera.', amount: 0, action: 'go_to_jail' },
  { type: 'setback', title: 'Burnout', text: 'O médico mandou desligar o celular por 2 rodadas.', amount: 0, action: 'freeze_player' },
  { type: 'setback', title: 'Agiota', text: 'Eles não aceitam desculpas. Pague 20% da sua dívida agora.', amount: 0.20, action: 'pay_loan_percent' },
  { type: 'setback', title: 'Reforma Estrutural', text: 'Cupins comeram as vigas. Pague $20k por casa.', amount: 20000, action: 'repairs_house' },
  { type: 'setback', title: 'Churrasco da Turma', text: 'Você prometeu pagar a carne. Pague para todos.', amount: 5000, action: 'pay_all' },
  { type: 'setback', title: 'Vazamento de Dados', text: 'Multa da LGPD por vazar dados de clientes.', amount: 150000, action: 'pay_bank' },
  { type: 'setback', title: 'Divórcio Litigioso', text: 'O amor acabou, e metade do dinheiro também.', amount: 250000, action: 'pay_bank' },
  { type: 'setback', title: 'Imposto de Renda', text: 'A malha fina te pegou. Pague o leão.', amount: 120000, action: 'pay_bank' },
  { type: 'setback', title: 'Festa de 15 Anos', text: 'Sua afilhada quer festa de princesa. Pague a todos.', amount: 15000, action: 'pay_all' },
  { type: 'setback', title: 'IPTU Atrasado', text: 'A prefeitura mandou a conta. Pague $15k por casa.', amount: 15000, action: 'repairs_house' },
  { type: 'luck', title: 'Viralizou no TikTok', text: 'Sua dancinha ridícula te rendeu patrocínios.', amount: 150000, action: 'receive_bank' },
  { type: 'luck', title: 'Jogo do Bicho', text: 'Deu no poste! A milhar seca veio.', amount: 50000, action: 'receive_bank' },
  { type: 'luck', title: 'Herança da Vó', text: 'Ela guardava dinheiro no colchão e deixou pra você.', amount: 500000, action: 'receive_bank' },
  { type: 'luck', title: 'Vendeu Pack', text: 'Fotos do pé... quem diria que valiam tanto?', amount: 30000, action: 'receive_bank' },
  { type: 'luck', title: 'Achou Bitcoin', text: 'Lembrou a senha da carteira de 2012. Ficou rico!', amount: 1000000, action: 'receive_bank' },
  { type: 'luck', title: 'Processou o Vizinho', text: 'Ganhou a causa por danos morais.', amount: 80000, action: 'receive_bank' },
  { type: 'luck', title: 'Restituição IR', text: 'O leão cochilou e te devolveu uma grana.', amount: 45000, action: 'receive_bank' },
  { type: 'luck', title: 'Erro no App', text: 'O banco transferiu errado e você sacou rápido.', amount: 200000, action: 'receive_bank' },
  { type: 'luck', title: 'Aniversário', text: 'Faça cara de pidão e cobre presente de todos.', amount: 10000, action: 'receive_all' },
  { type: 'luck', title: 'Bônus PLR', text: 'A empresa bateu a meta!', amount: 120000, action: 'receive_bank' },
  { type: 'luck', title: 'Investidor Anjo', text: 'Sua ideia de startup recebeu aporte.', amount: 350000, action: 'receive_bank' },
  { type: 'luck', title: 'Casamento Rico', text: 'Golpe do baú bem sucedido! Receba presentes de todos.', amount: 25000, action: 'receive_all' },
  { type: 'luck', title: 'Achado não é Roubado', text: 'Achou uma mala de dinheiro no parque.', amount: 180000, action: 'receive_bank' },
  { type: 'luck', title: 'Prêmio Nobel', text: 'Você inventou a cura da calvície.', amount: 600000, action: 'receive_bank' },
  { type: 'luck', title: 'Achou Dinheiro', text: 'Estava no bolso daquela calça velha.', amount: 5000, action: 'receive_bank' },
  { type: 'luck', title: 'Vendeu NFT', text: 'Um jpeg de macaco valia uma fortuna.', amount: 120000, action: 'receive_bank' },
  { type: 'luck', title: 'Bingo da Igreja', text: 'Ganhou o prêmio principal: um frango assado (em dinheiro).', amount: 2000, action: 'receive_bank' },
  { type: 'luck', title: 'Startup Unicórnio', text: 'Sua empresa de tecnologia decolou!', amount: 400000, action: 'receive_bank' },
  { type: 'luck', title: 'Reembolso Aéreo', text: 'A companhia aérea cancelou seu voo e pagou indenização.', amount: 30000, action: 'receive_bank' },
  { type: 'luck', title: 'Aposta Esportiva', text: 'A zebra ganhou e você faturou alto.', amount: 45000, action: 'receive_bank' },
  { type: 'luck', title: 'Vendeu Curso', text: 'Lançou um curso de "Como ficar rico dormindo".', amount: 250000, action: 'receive_bank' },
  { type: 'luck', title: 'Tio Distante', text: 'Um parente que você nem conhecia te deixou uma herança.', amount: 300000, action: 'receive_bank' },
  { type: 'luck', title: 'Processo Ganho', text: 'A operadora de telefonia te cobrou indevidamente e pagou em dobro.', amount: 15000, action: 'receive_bank' },
  { type: 'luck', title: 'Sorteio do Mercado', text: 'Ganhou um vale-compras.', amount: 1000, action: 'receive_bank' },
  { type: 'luck', title: 'Restituição de Imposto', text: 'O governo errou a conta a seu favor.', amount: 25000, action: 'receive_bank' },
  { type: 'luck', title: 'Vendeu Ideia', text: 'Uma grande empresa comprou sua patente.', amount: 150000, action: 'receive_bank' },
  { type: 'luck', title: 'Achou Joia', text: 'Encontrou um anel de ouro na praia.', amount: 8000, action: 'receive_bank' },
  { type: 'luck', title: 'Prêmio de Loteria', text: 'Acertou a quadra na Mega-Sena.', amount: 60000, action: 'receive_bank' },
  { type: 'luck', title: 'Vendeu Carro Velho', text: 'Conseguiu um bom preço na sua lata velha.', amount: 20000, action: 'receive_bank' },
  { type: 'setback', title: 'Golpe do Príncipe', text: 'Acreditou no e-mail do príncipe nigeriano.', amount: 50000, action: 'pay_bank' },
  { type: 'setback', title: 'Mecânico', text: 'O motor do carro fundiu.', amount: 35000, action: 'pay_bank' },
  { type: 'setback', title: 'Perdeu a Carteira', text: 'Esqueceu no Uber e nunca mais viu.', amount: 2000, action: 'pay_bank' },
  { type: 'setback', title: 'Pirâmide Financeira', text: 'Era golpe. Perdeu tudo que investiu.', amount: 100000, action: 'pay_bank' },
  { type: 'setback', title: 'Multa de Trânsito', text: 'Passou no sinal vermelho.', amount: 5000, action: 'pay_bank' },
  { type: 'setback', title: 'Casamento Surpresa', text: 'Foi convidado e teve que comprar presente caro. Pague a todos.', amount: 2000, action: 'pay_all' },
  { type: 'setback', title: 'Vazamento no Teto', text: 'Infiltração no apartamento de baixo. Pague $10k por casa.', amount: 10000, action: 'repairs_house' },
  { type: 'setback', title: 'Streaming Esquecido', text: 'Pagou 5 anos de assinatura sem usar.', amount: 15000, action: 'pay_bank' },
  { type: 'setback', title: 'Terreno na Lua', text: 'Comprou um lote lunar que não existe.', amount: 40000, action: 'pay_bank' },
  { type: 'setback', title: 'Imposto Extra', text: 'Taxa de grandes fortunas. Pague ao banco.', amount: 200000, action: 'pay_bank' },
  { type: 'setback', title: 'Dentista', text: 'Canal no dente. Doeu no bolso.', amount: 12000, action: 'pay_bank' },
  { type: 'setback', title: 'Celular Quebrado', text: 'Caiu na privada.', amount: 8000, action: 'pay_bank' },
  { type: 'setback', title: 'Roubo de Identidade', text: 'Fizeram compras no seu cartão.', amount: 60000, action: 'pay_bank' },
  { type: 'setback', title: 'Aposta Perdida', text: 'Apostou no time errado.', amount: 25000, action: 'pay_bank' },
  { type: 'setback', title: 'Festa Estragada', text: 'A polícia chegou e multou por barulho.', amount: 10000, action: 'pay_bank' },
  { type: 'luck', title: 'IPO Lendário', text: 'Sua startup abriu capital na NASDAQ! O mercado enlouqueceu.', amount: 1500000, action: 'receive_bank' },
  { type: 'luck', title: 'Bilhete Dourado', text: 'Você encontrou o bilhete premiado da loteria acumulada!', amount: 2000000, action: 'receive_bank' },
  { type: 'luck', title: 'Mecenas Anônimo', text: 'Um admirador secreto decidiu financiar seu estilo de vida.', amount: 800000, action: 'receive_bank' },
  { type: 'luck', title: 'Guru dos Negócios', text: 'Todos querem seus conselhos. Cobre consultoria de cada jogador.', amount: 50000, action: 'receive_all' },
  { type: 'luck', title: 'Bitcoin na Lua', text: 'Aquela carteira perdida de 2010 foi recuperada na alta histórica!', amount: 1200000, action: 'receive_bank' },
  { type: 'setback', title: 'Crash da Bolsa', text: 'Segunda-feira negra! Seus investimentos viraram pó.', amount: 800000, action: 'pay_bank' },
  { type: 'setback', title: 'Escândalo Corporativo', text: 'Seu nome vazou em delações premiadas. Pague advogados de elite.', amount: 600000, action: 'pay_bank' },
  { type: 'setback', title: 'Desastre Natural', text: 'Um furacão atingiu suas propriedades. Pague $40k por casa para reconstruir.', amount: 40000, action: 'repairs_house' },
  { type: 'setback', title: 'Indenização Coletiva', text: 'Seu produto causou alergia em massa. Pague indenização a todos os jogadores.', amount: 40000, action: 'pay_all' },
  { type: 'setback', title: 'Confisco de Bens', text: 'A receita federal congelou seus ativos por sonegação.', amount: 500000, action: 'pay_bank' },
  
  // --- NOVOS ITENS DE INVENTÁRIO ---
  { type: 'item', title: 'Habeas Corpus', text: 'Um contato quente na polícia. Livre-se da prisão.', action: 'add_inventory', itemId: 'habeas_corpus' },
  { type: 'item', title: 'Compra Livre!', text: 'O dono ficou maluco! Compre qualquer imóvel ocupado.', action: 'add_inventory', itemId: 'free_buy' },
  { type: 'item', title: 'Usucapião', text: 'Documentação forjada com sucesso. Roube um imóvel.', action: 'add_inventory', itemId: 'steal_prop' },
  { type: 'item', title: 'Cartão Black', text: 'O banco perdoou sua dívida por engano.', action: 'add_inventory', itemId: 'black_card' },

  // --- NOVAS CARTAS ÉPICAS ---
  { type: 'luck', title: 'Mega da Virada', text: 'Você acertou as 6 dezenas sozinho! O Brasil parou.', amount: 2500000, action: 'receive_bank' },
  { type: 'luck', title: 'Mineração Espacial', text: 'Sua empresa encontrou ouro em um asteroide.', amount: 1800000, action: 'receive_bank' },
  { type: 'luck', title: 'Herança Real', text: 'Descobriu que é parente distante da realeza britânica.', amount: 1200000, action: 'receive_bank' },
  { type: 'setback', title: 'Crise Global', text: 'O mercado financeiro colapsou mundialmente.', amount: 1000000, action: 'pay_bank' },
  { type: 'setback', title: 'Ataque Hacker', text: 'Ransomware sequestrou todos os seus dados.', amount: 700000, action: 'pay_bank' },
  { type: 'setback', title: 'Esquema Ponzi', text: 'A pirâmide caiu e você estava no topo... da dívida.', amount: 800000, action: 'pay_bank' },

  // --- NOVAS CARTAS COMUNS ---
  { type: 'luck', title: 'Cashback', text: 'Recebeu dinheiro de volta nas compras do mês.', amount: 5000, action: 'receive_bank' },
  { type: 'luck', title: 'Vendeu Móveis', text: 'Desapegou daquele sofá velho na OLX.', amount: 8000, action: 'receive_bank' },
  { type: 'luck', title: 'Rifa da Escola', text: 'Ganhou uma cesta de café da manhã e vendeu.', amount: 2000, action: 'receive_bank' },
  { type: 'luck', title: 'Freelance', text: 'Fez um bico no fim de semana.', amount: 15000, action: 'receive_bank' },
  { type: 'luck', title: 'Achou Carteira', text: 'Tinha pouco dinheiro, mas é seu agora.', amount: 3000, action: 'receive_bank' },
  { type: 'setback', title: 'Assinatura VIP', text: 'Esqueceu de cancelar o trial grátis de 10 apps.', amount: 4000, action: 'pay_bank' },
  { type: 'setback', title: 'Tela Trincada', text: 'O celular caiu de cara no chão. Sem seguro.', amount: 6000, action: 'pay_bank' },
  { type: 'setback', title: 'Veterinário', text: 'O cachorro engoliu uma meia.', amount: 12000, action: 'pay_bank' },
  { type: 'setback', title: 'Pneu Furado', text: 'Teve que trocar os dois pneus da frente.', amount: 8000, action: 'pay_bank' },
  { type: 'setback', title: 'Taxa de Condomínio', text: 'Chamada extra para pintar o prédio.', amount: 10000, action: 'pay_bank' }
];

export const HOLIDAY_CARDS = [
  { type: 'setback', title: 'Feriado', text: 'Hora de relaxar! Pague as despesas da viagem.', amount: 20000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Fim de semana na praia. O hotel foi caro.', amount: 15000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Viagem internacional. O dólar estava alto.', amount: 30000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Acampamento de luxo (Glamping). Custou um rim.', amount: 25000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Cruzeiro all-inclusive. Coma à vontade, pague à vontade.', amount: 35000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Retiro espiritual. A paz custa caro.', amount: 10000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Festival de música. Ingressos VIP.', amount: 18000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Esqui nos Alpes. Frio e caro.', amount: 40000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Turismo gastronômico. A conta do restaurante assustou.', amount: 12000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Parque de diversões. Filas e preços abusivos.', amount: 22000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Hotel Fazenda. Mosquito e conta alta.', amount: 14000, action: 'pay_bank', note: 'Feriado' },
  { type: 'setback', title: 'Feriado', text: 'Ecoturismo. Se perdeu e pagou o resgate.', amount: 28000, action: 'pay_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Overbooking no voo! Recebeu indenização e upgrade.', amount: 5000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Ganhou um sorteio no hotel: estadia grátis!', amount: 15000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Achou uma carteira na praia e devolveu. Ganhou recompensa.', amount: 2000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Promoção relâmpago! O banco devolveu parte das taxas.', amount: 8000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Cassino do navio. A sorte sorriu para você.', amount: 25000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Guia turístico era seu fã. Passeio de graça e presentes.', amount: 3000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Comprou lembrancinhas raras que valem muito.', amount: 10000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'A companhia aérea extraviou a mala, mas pagou bem.', amount: 12000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Upgrade para classe executiva sem custo.', amount: 5000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Ganhou um voucher de jantar no resort.', amount: 1500, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Vendeu suas milhas aéreas acumuladas.', amount: 4000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Seguro viagem reembolsou despesas médicas.', amount: 6000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Show cancelado. Reembolso em dobro.', amount: 3000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Amigo rico pagou todas as contas do bar.', amount: 2000, action: 'receive_bank', note: 'Feriado' },
  { type: 'luck', title: 'Feriado', text: 'Encontrou um tesouro num mergulho.', amount: 50000, action: 'receive_bank', note: 'Feriado' },
];

export const VISIT_CARDS = [
  { type: 'luck', title: 'Visita Social', text: 'Recebeu amigos em casa.', amount: 5000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Jantar comemorativo. Os convidados trouxeram presentes.', amount: 8000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Reunião de negócios informal. Fechou um pequeno contrato.', amount: 10000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Visita da família. A vovó deixou um agrado.', amount: 6000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Festa surpresa. Ganhou vaquinha dos amigos.', amount: 7000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Hospedou um turista. Airbnb improvisado.', amount: 12000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Noite de jogos. Ganhou as apostas.', amount: 4000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Chá de bebê. Ganhou fraldas (que valem ouro).', amount: 3000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Encontro de ex-alunos. Networking rendeu frutos.', amount: 9000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Vizinho agradecido. Cuidou do cachorro dele.', amount: 2000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Influencer visitou. Ganhou permuta.', amount: 15000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'luck', title: 'Visita Social', text: 'Achou dinheiro no sofá depois da visita.', amount: 1000, action: 'receive_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'A visita quebrou seu vaso Ming. Prejuízo.', amount: 15000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Seu cachorro mordeu a visita. Pague o médico.', amount: 5000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Festa saiu do controle. Vizinhos chamaram a polícia (multa).', amount: 2000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'A visita era um vendedor de seguros chato. Comprou por educação.', amount: 3000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Mancha de vinho no tapete persa.', amount: 8000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'A visita comeu todo o seu estoque de caviar.', amount: 10000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Entupiram o banheiro. Encanador de emergência.', amount: 4000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Emprestaram dinheiro e nunca mais devolveram.', amount: 5000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Quebraram sua TV nova jogando Wii.', amount: 12000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Ar condicionado pifou de tanto usarem.', amount: 6000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Pediram delivery caro e você pagou.', amount: 2500, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'A visita ficou uma semana a mais. Gastos extras.', amount: 7000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Criança da visita riscou a parede.', amount: 1500, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Levaram suas toalhas bordadas "sem querer".', amount: 1000, action: 'pay_bank', note: 'Visita Social' },
  { type: 'setback', title: 'Visita Social', text: 'Pagou o Uber Black para a visita ir embora.', amount: 500, action: 'pay_bank', note: 'Visita Social' },
];

export const NEIGHBORHOOD_SERVICES = {
    purple: { label: 'Cultural', level1: { name: 'Biblioteca', threshold: 2, bonus: 0.2 }, level2: { name: 'Universidade', threshold: 4, bonus: 0.5 } },
    light_green: { label: 'Litoral', level1: { name: 'Salva-Vidas', threshold: 3, bonus: 0.2 }, level2: { name: 'Resort', threshold: 6, bonus: 0.5 } },
    pink: { label: 'Nobre', level1: { name: 'Boutique', threshold: 2, bonus: 0.2 }, level2: { name: 'Shopping', threshold: 4, bonus: 0.5 } },
    red: { label: 'Comércio', level1: { name: 'Mecânica', threshold: 3, bonus: 0.2 }, level2: { name: 'Corporativo', threshold: 6, bonus: 0.5 } },
    dark_green: { label: 'Financeiro', level1: { name: 'Caixa Elet.', threshold: 3, bonus: 0.2 }, level2: { name: 'Bolsa', threshold: 6, bonus: 0.5 } },
    dark_blue: { label: 'Histórico', level1: { name: 'Posto Pol.', threshold: 3, bonus: 0.2 }, level2: { name: 'Delegacia', threshold: 6, bonus: 0.5 } },
    yellow: { label: 'Turismo', level1: { name: 'Táxi', threshold: 3, bonus: 0.2 }, level2: { name: 'Aeroporto', threshold: 6, bonus: 0.5 } },
    orange: { label: 'Cívico', level1: { name: 'Posto Saúde', threshold: 3, bonus: 0.2 }, level2: { name: 'Hospital', threshold: 6, bonus: 0.5 } },
    company: { label: 'Indústria', level1: { name: 'Galpão', threshold: 1, bonus: 0.1 }, level2: { name: 'Usina', threshold: 3, bonus: 0.2 } },
    special: { label: 'Tech', level1: { name: 'Startup', threshold: 1, bonus: 0.1 }, level2: { name: 'Campus', threshold: 2, bonus: 0.2 } }
};
